In [87]:
from time import gmtime, strftime
from datetime import datetime
import datetime
import requests
import pandas as pd
import json
import jwt
import time
import ssl

from datetime import datetime
from pytz import timezone
# format = "%Y-%m-%d %H:%M:%S %Z%z"
format = "%Y-%m-%d"
# Current time in UTC
now_utc = datetime.now(timezone('UTC'))
# print(now_utc.strftime(format))
# Convert to Asia/Kolkata time zone
now_asia = now_utc.astimezone(timezone('Asia/Kolkata'))
Today = str(now_asia.strftime(format))

# now = datetime.now()
# Time = now.strftime("%a %b %d %Y %I:%M GMT(%Z)\n")
# Time = strftime("%a %b %d %Y %I:%M:%S GMT(%Z)\n")
# tokenCreationTime = str(datetime.now().time())
# import time
print("******************************")
print("Today Date is :",Today)
print("******************************")
# URL = "https://api.ristaapps.com/v1/inventory/item/activity"
# URL = "https://api.ristaapps.com/v1/items/soldout"
# URL = "https://api.ristaapps.com/v1/sales/page"
# URL = "https://api.ristaapps.com/v1"


# URL = "https://api.ristaapps.com/v1/inventory/item/activity"


apiKey = 'e1b9bba5-206f-47a7-9904-633b3d95a8c7'
secretKey = 'mdgGj4sOp5Ly4ed-s2lYFuDrON8nic56L9lJ81nEMmY'

tokenCreationTime = int(round(time.time()))
# print(tokenCreationTime)

payload = {"iss": apiKey, "iat": tokenCreationTime}

token =   jwt.encode(payload, secretKey) 
#*************************************************************************************
# BRANCH_URL = "https://api.ristaapps.com/v1/branch/list"
# head = {"x-api-token": token, "x-api-key": apiKey,  'content-type': 'application/json'}
# response=requests.get(BRANCH_URL,headers=head).json()
# df = pd.json_normalize(response)
# Branch_Code=[]
# for i in df['branchCode']:
#     Branch_Code.append(str(i))
# print(Branch_Code)
Branch_Code= ['AL1','ASH','CHN','CLJ','CP','CSP',
              'DDT','DK','GC1','GDK','GFP','GN',
              'GTB','HO','IN','IP','JAK','JNK',
              'KK','KN','LN','MJ','MN','MVD',
              'N137','N18','N50','NCR WH','NFC',
              'NIT','PV','RA','RDS','RG','RJN','ROH',
              'RP','S122','S49','S7GGN','S81','S83',
              'S9CHD','SC','SCC','SDR','Sec31FBD','SLK','SP','VK']
#*************************************************************************************    
URL = "https://api.ristaapps.com/v1/inventory/shrinkage/page"

# appended_data.append(data)# loop
# appended_data = pd.concat(appended_data)
appended_data = []
for BC in Branch_Code:
    try:
        print("Working Branch :",BC)
        #run your code
        paras = {"branch": BC, "day":'2021-11-10'}
        head = {"x-api-token": token, "x-api-key": apiKey,  'content-type': 'application/json'}
        response = requests.get(URL, params=paras, headers=head).json()
        file = response['data']
        df = pd.json_normalize(file)
        appended_data.append(df)# loop
        
#         print(appended_data)
        
    except:
#         print('Erro')
        print("Not Working Branch :",BC)
        pass
# requests.get(URL, params=paras, headers=head).json()
# print(response.text)

# response = requests.get(URL, headers={'x-api-key': apiKey ,'x-api-token': jwt.encode({ "iss": apiKey, "iat": int(round(time.time())) }, secretKey, algorithm="HS256")}, data={ "iss": apiKey, "iat": int(round(time.time()))})
# print(response.json())
# (response).json()
# print(response.text)
# print(response)
appended_data = pd.concat(appended_data)
print('****************** COMPLETE **********************')
    # print(response)

******************************
Today Date is : 2021-11-17
******************************
Working Branch : AL1
Working Branch : ASH
Working Branch : CHN
Working Branch : CLJ
Working Branch : CP
Working Branch : CSP
Working Branch : DDT
Working Branch : DK
Working Branch : GC1
Working Branch : GDK
Working Branch : GFP
Working Branch : GN
Working Branch : GTB
Working Branch : HO
Working Branch : IN
Working Branch : IP
Working Branch : JAK
Working Branch : JNK
Working Branch : KK
Working Branch : KN
Working Branch : LN
Working Branch : MJ
Working Branch : MN
Working Branch : MVD
Working Branch : N137
Working Branch : N18
Working Branch : N50
Working Branch : NCR WH
Working Branch : NFC
Working Branch : NIT
Working Branch : PV
Working Branch : RA
Working Branch : RDS
Working Branch : RG
Working Branch : RJN
Working Branch : ROH
Working Branch : RP
Working Branch : S122
Working Branch : S49
Working Branch : S7GGN
Working Branch : S81
Working Branch : S83
Working Branch : S9CHD
Working Branch : SC
Working Branch : SCC
Working Branch : SDR
Working Branch : Sec31FBD
Working Branch : SLK
Working Branch : SP
Working Branch : VK
****************** COMPLETE **********************

In [88]:
appended_data

,branchCode,branchName,shrinkageNumber,shrinkageDate,shrinkageBusinessDay,totalAmount,status,items
0,AL1,Alpha 1,9330,2021-11-11T04:47:57+05:30,2021-11-10,-56.02,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,ASH,Ashiyana,9284,2021-11-11T02:00:18+05:30,2021-11-10,-975.96,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,CHN,Channi Jammu,9245,2021-11-10T22:33:24+05:30,2021-11-10,-436.27,Final,"[{'measuringUnit': 'Piece', 'skuCode': '304', ..."
0,CLJ,Civil Lines,9248,2021-11-10T23:20:01+05:30,2021-11-10,-238.58,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,DDT,Devrana DT,9253,2021-11-10T23:46:42+05:30,2021-11-10,-65.26,Final,"[{'measuringUnit': 'Kilogram', 'skuCode': '309..."
0,DK,Dwarka,9339,2021-11-11T05:24:27+05:30,2021-11-10,-820.44,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,GC1,Gaur City 1 Gr Noida,9308,2021-11-11T03:37:40+05:30,2021-11-10,-81.74,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,GDK,Gandhidham Kachchh,9266,2021-11-11T00:27:27+05:30,2021-11-10,-4099.05,Final,"[{'measuringUnit': 'Piece', 'skuCode': '242', ..."
0,GN,Gomti Nagar,9319,2021-11-11T04:28:51+05:30,2021-11-10,-131.69,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,GTB,GTB Nagar,9299,2021-11-11T03:29:26+05:30,2021-11-10,-110.08,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
1,GTB,GTB Nagar,9304,2021-11-11T03:32:52+05:30,2021-11-10,-315.00,Final,"[{'measuringUnit': 'Kilogram', 'skuCode': '251..."
0,IN,Indira Nagar,9265,2021-11-11T00:26:53+05:30,2021-11-10,-165.31,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,JAK,Jakhan DDN,9262,2021-11-11T00:13:46+05:30,2021-11-10,-132.35,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,JNK,Janakpuri,9328,2021-11-11T04:44:24+05:30,2021-11-10,-164.26,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,KK,Kalkaji,9291,2021-11-11T03:14:08+05:30,2021-11-10,-246.86,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,KN,Krishna Nagar,9317,2021-11-11T04:23:37+05:30,2021-11-10,-151.86,Final,"[{'measuringUnit': 'Piece', 'skuCode': '242', ..."
1,KN,Krishna Nagar,9323,2021-11-11T04:33:20+05:30,2021-11-10,-2226.42,Final,"[{'measuringUnit': 'Tin', 'skuCode': '338', 'i..."
0,LN,Lajpat Nagar,9298,2021-11-11T03:27:31+05:30,2021-11-10,-191.54,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,MJ,Malviya Nagar JP,9275,2021-11-11T01:00:10+05:30,2021-11-10,-26.68,Final,"[{'measuringUnit': 'Kilogram', 'skuCode': '309..."
0,MN,Malviya Nagar,9314,2021-11-11T04:05:35+05:30,2021-11-10,-163.60,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,MVD,Mayur Vihar,9287,2021-11-11T02:43:15+05:30,2021-11-10,-29.15,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,N137,Sector 137 Noida,9286,2021-11-11T02:38:24+05:30,2021-11-10,-60.50,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,N18,Sec 18 Noida,9258,2021-11-11T00:03:40+05:30,2021-11-10,-10.36,Final,"[{'measuringUnit': 'Kilogram', 'skuCode': '309..."
0,N50,Sec 50 Noida,9249,2021-11-10T23:27:48+05:30,2021-11-10,-127.60,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,NFC,New Friends Colony,9345,2021-11-11T06:12:22+05:30,2021-11-10,-4.90,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,PV,Palam Vihar,9315,2021-11-11T04:10:39+05:30,2021-11-10,-145.39,Final,"[{'measuringUnit': 'Kilogram', 'skuCode': '255..."
0,RA,Ranjit Avenue Amritsar,9289,2021-11-11T02:58:34+05:30,2021-11-10,-149.36,Final,"[{'measuringUnit': 'Piece', 'skuCode': '242', ..."
0,RJN,Raj Nagar,9321,2021-11-11T04:31:34+05:30,2021-11-10,-79.18,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,ROH,Rohini,9336,2021-11-11T05:12:26+05:30,2021-11-10,-144.18,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,RP,Rajendra Place,9272,2021-11-11T00:35:04+05:30,2021-11-10,-2694.82,Final,"[{'measuringUnit': 'Piece', 'skuCode': '242', ..."
0,S122,Sec 122 Noida,9247,2021-11-10T22:56:50+05:30,2021-11-10,-96.82,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,S49,Sec 49 GGN,9293,2021-11-11T03:22:04+05:30,2021-11-10,-324.24,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,S7GGN,Sec 7 GGN,9269,2021-11-11T00:32:09+05:30,2021-11-10,-108.62,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,S81,Sec 81 FBD,9325,2021-11-11T04:35:00+05:30,2021-11-10,-131.60,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,S83,Sec 83 GGN,9309,2021-11-11T03:41:39+05:30,2021-11-10,-176.62,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,S9CHD,Sec 9 CHD,9211,2021-11-10T18:25:19+05:30,2021-11-10,-427.36,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
1,S9CHD,Sec 9 CHD,9337,2021-11-11T05:23:24+05:30,2021-11-10,-3416.48,Final,"[{'measuringUnit': 'Piece', 'skuCode': '242', ..."
0,SC,Suncity,9290,2021-11-11T03:10:10+05:30,2021-11-10,-312.41,Final,"[{'measuringUnit': 'Kilogram', 'skuCode': '255..."
0,Sec31FBD,Sec 31 FBD,9302,2021-11-11T03:30:26+05:30,2021-11-10,-22.70,Final,"[{'measuringUnit': 'Piece', 'skuCode': '304', ..."
0,SLK,Sushant Lok,9318,2021-11-11T04:27:58+05:30,2021-11-10,-110.74,Final,"[{'measuringUnit': 'Kilogram', 'skuCode': '255..."
0,SP,Shradhanand Peth,9303,2021-11-11T03:32:45+05:30,2021-11-10,-73.44,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."
0,VK,Vasant Kunj,9342,2021-11-11T05:39:40+05:30,2021-11-10,-100.14,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."

In [ ]:
column_= appended_data.columns
COLUMN_NAMES= ['branchName', 'branchCode', 'invoiceNumber', 'invoiceDate',
       'invoiceType', 'chargeAmount', 'grossAmount', 'discountAmount',
       'taxAmount', 'netAmount', 'roundOffAmount', 'tipAmount', 'totalAmount',
       'customerId', 'customerName', 'saleBy', 'channel', 'label', 'status',
       'sessionLabel']
DF = pd.DataFrame(columns=COLUMN_NAMES)

In [ ]:
for column in COLUMN_NAMES:
    if column  in column_:
        value= appended_data[column]
        #         DF.insert(count,column,value)
        DF[column]=value

In [80]:
from time import gmtime, strftime
from datetime import datetime
import datetime
import requests
import pandas as pd
import json
import jwt
import time
import ssl

from datetime import datetime
from pytz import timezone
format = "%Y-%m-%d"
now_utc = datetime.now(timezone('UTC'))
now_asia = now_utc.astimezone(timezone('Asia/Kolkata'))
Today = str(now_asia.strftime(format))

URL = "https://api.ristaapps.com/v1/inventory/shrinkage/page"
apiKey = 'e1b9bba5-206f-47a7-9904-633b3d95a8c7'
secretKey = 'mdgGj4sOp5Ly4ed-s2lYFuDrON8nic56L9lJ81nEMmY'

tokenCreationTime = int(round(time.time()))
payload = {"iss": apiKey, "iat": tokenCreationTime}
token =   jwt.encode(payload, secretKey) 

paras = {"branch": 'MVD', "day":'2021-11-10'}
head = {"x-api-token": token, "x-api-key": apiKey,  'content-type': 'application/json'}
response=requests.get(URL,params=paras,headers=head).json()

data=response['data']
#  =data['items']
df = pd.json_normalize(data)

In [81]:
bc= df['branchName'][0]
data_file =response['data'][0]['items']
df_ = pd.json_normalize(data_file)
df_['branchName']= bc
df_

,measuringUnit,skuCode,itemName,quantity,unitCost,itemAmount,label,branchName
0,Piece,290,Bun 4,-2,4.90,-9.80,Damaged,Mayur Vihar
1,Piece,298,Cheese N Veg Delight Patty - Small,-1,19.35,-19.35,Damaged,Mayur Vihar

In [82]:
df

,branchCode,branchName,shrinkageNumber,shrinkageDate,shrinkageBusinessDay,totalAmount,status,items
0,MVD,Mayur Vihar,9287,2021-11-11T02:43:15+05:30,2021-11-10,-29.15,Final,"[{'measuringUnit': 'Piece', 'skuCode': '290', ..."

In [85]:
Final_DF = pd.merge(df,  df_,  on ='branchName',  how ='inner')
name_column = Final_DF.pop('branchName')
Final_DF.insert(1, 'branchName', name_column)
Final_DF.drop('items',axis='columns', inplace=True)
Final_DF

,branchCode,branchName,shrinkageNumber,shrinkageDate,shrinkageBusinessDay,totalAmount,status,measuringUnit,skuCode,itemName,quantity,unitCost,itemAmount,label
0,MVD,Mayur Vihar,9287,2021-11-11T02:43:15+05:30,2021-11-10,-29.15,Final,Piece,290,Bun 4,-2,4.90,-9.80,Damaged
1,MVD,Mayur Vihar,9287,2021-11-11T02:43:15+05:30,2021-11-10,-29.15,Final,Piece,298,Cheese N Veg Delight Patty - Small,-1,19.35,-19.35,Damaged